### PR TITLE
Port from ava to jest

### PR DESCRIPTION
**Pull request by wincent**
Will need this for: https://github.com/liferay/liferay-js-themes-toolkit/issues/193

### CODE REVIEW

**Comment by wincent** [comment]
cc @julien

@jbalsas we don't have to actually merge this here: i just wanted to see the tests passing before I go copying a bunch of files over into the other repo.

**Comment by jbalsas** [comment]
Did they run at all? 🙈

**Comment by wincent** [comment]
@jbalsas: they did not work before this PR, at least for me. But they do now:

```
> liferay-plugin-node-tasks@2.1.0 test /Users/greghurrell/code/liferay-plugin-node-tasks
> jest

 PASS  test/lib/register_hooks.js
 PASS  test/lib/gogo_deploy.js
 PASS  test/tasks/init.js
 PASS  test/lib/init_prompt.js
 PASS  test/index.js
  ● Console

    console.log node_modules/fancy-log/index.js:36
      Deploying to /var/folders/yc/1x2y2qld1g95tvtjpd89hdrm0000gp/T/liferay-plugin-tasks/appserver/deploy

 PASS  test/tasks/deploy.js
  ● Console

    console.log node_modules/fancy-log/index.js:36
      Deploying to /var/folders/yc/1x2y2qld1g95tvtjpd89hdrm0000gp/T/liferay-plugin-tasks/deploy-task/appserver/deploy
    console.log node_modules/fancy-log/index.js:36
      Deployed via gogo shell

 PASS  test/tasks/version.js
  ● Console

    console.log node_modules/fancy-log/index.js:36
      Warning: the value of module-version in liferay-plugin-package.properties does not match version in package.json. Using version from package.json

 PASS  test/tasks/war.js

Test Suites: 8 passed, 8 total
Tests:       41 passed, 41 total
Snapshots:   0 total
Time:        2.958s
Ran all test suites.
```

**Comment by wincent** [comment]
Just so we can see the totality of the changes, I pushed some separate PRs to my fork:

- https://github.com/wincent/liferay-plugin-node-tasks/pull/2 ("Port from ava to jest", ie. identical to this PR)
- https://github.com/wincent/liferay-plugin-node-tasks/pull/1 ("Remove all references to gogo-shell", despite the lower PR number, builds on top of the ava-to-jest PR above)

**Comment by wincent** [comment]
Closing this to clear out my [open PRs list](https://github.com/pulls).

sad

**Pull request closed without merging**
